# Generated by Django 4.1 on 2022-08-09 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='lifestyle',
            field=models.CharField(choices=[('NA', ''), ('HED', 'hedonistic'), ('ADV', 'adventuristic'), ('IND', 'individualistic'), ('PRO', 'promethean')], default='NA', max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='web.job'),
        ),
    ]
