# Generated by Django 4.1 on 2022-08-09 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_hobby_user_lifestyle_alter_user_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='description1',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='description2',
        ),
        migrations.CreateModel(
            name='UserWithHobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usrs', to='web.hobby')),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hobbies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
