# Generated by Django 4.1 on 2022-08-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_user_description_alter_user_personality'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('NA', ''), (0, 'Male'), (1, 'Female'), (2, 'Other'), (3, 'Prefer no to answer')], default='NA', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='personality',
            field=models.CharField(choices=[('NA', ''), ('INTP', 'INTP'), ('INTJ', 'INTJ'), ('ENTJ', 'ENTJ'), ('ENTP', 'ENTP'), ('INFJ', 'INFJ'), ('INFP', 'INFP'), ('ENFJ', 'ENFJ'), ('ENFP', 'ENFP'), ('ISTJ', 'ISTJ'), ('ISFJ', 'ISFJ'), ('ESTJ', 'ESTJ'), ('ESFJ', 'ESFJ'), ('ISTP', 'ISTP'), ('ISFP', 'ISFP'), ('ESTP', 'ESTP'), ('ESFP', 'ESFP')], default='NA', max_length=4),
        ),
    ]
